### ISSUE TITLE
kong GW pod is not connecting to control plane

### ISSUE THREAD

**Issue by jalawala** [aws-samples/terraform-eks-blueprints-kong-samples#8]
@anshrma @DaniellaFreese 

I see below error in Gateway pod

192.168.54.161 - - [21/Nov/2023:16:13:08 +0000] "GET /status HTTP/2.0" 200 1926 "-" "Go-http-client/2.0"
2023/11/21 16:13:09 [error] 2320#0: *36586 [lua] telemetry.lua:222: connection to control plane wss://1e90db7081.us.tp0.konghq.com:443/v1/analytics/reqlog?node_id=7f4e68ec-78dd-49d2-bcbb-ac72eb15d8f9&node_hostname=kong-gateway-84df6ffbfb-fcxdn&node_version=3.4.2.0 broken: unexpected HTTP response code: 401 retrying after 8 seconds, context: ngx.timer
192.168.54.161 - - [21/Nov/2023:16:13:10 +0000] "GET /status HTTP/2.0" 200 1926 "-" "Go-http-client/2.0"
192.168.54.161 - - [21/Nov/2023:16:13:13 +0000] "GET /status HTTP/2.0" 200 1926 "-" "Go-http-client/2.0"

I followed all instructions and see that secrets from AWS secret managers are mounted properly and certs are uploaded into konnect Admin portal.

With this the KIC runtime group is not connected to konnect control plane

**Comment by anshrma** [comment]
The instructions (in README.md in this folder) to use the cert generator utility were not up to date, which means that the runtime that will get created at Konnect end will not be of type KIC VS this folder installs helm chart that will specifically intended to work with KIC runtime group type.. I have updated the instructions with https://github.com/aws-samples/terraform-eks-blueprints-kong-samples/pull/9 and also tested these instructions out end to end to be working good. Please give it a spin afresh. Also, ensure to delete the specific gateway manager (or runtime) that you created before you try again. Thanks

**Comment by jalawala** [comment]
@anshrma  thanks its working now
